#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

INPUT_LEN_OVERRIDE=128 \
OUTPUT_LEN_OVERRIDE=32 \
NUM_PROMPTS_OVERRIDE=12 \
NUM_WARMUPS_OVERRIDE=2 \
REPETITIONS_OVERRIDE=1 \
CONCURRENCIES_OVERRIDE="1 8 32" \
BETWEEN_RUN_SECONDS_OVERRIDE=3 \
    "${SCRIPT_DIR}/run_baseline.sh"

